stages:
  - lint
  - test


.install_deps: &install_deps
  - pip install virtualenv
  - virtualenv .venv
  - export PATH="$(pwd)/bin:$PATH"
  - pip install -r requirements-dev.txt


.base:
  cache:
    key:
      files:
        - requirements.txt
        - requirements-dev.txt
    paths:
      - .venv
  before_script:
    - *install_deps


.test:
  extends: .base
  script: pytest
  stage: test


check_formatting:
  extends: .base
  image: python:3.9-slim
  script: black --check tests/ flag_engine/
  stage: lint


check_linting:
  extends: .base
  image: python:3.9-slim
  script: flake8 tests/ flag_engine/
  stage: lint


test:python36:
  extends: .test
  image: python:3.6-slim


test:python37:
  extends: .test
  image: python:3.7-slim
      
      
test:python38:
  extends: .test
  image: python:3.8-slim


test:python39:
  extends: .test
  image: python:3.9-slim
