stages:
  - test

image: ubuntu:20.04

.install_pyenv: &install_pyenv
  - apt-get update
  - apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev
  - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
  - export PYENV_ROOT="$HOME/.pyenv"
  - export PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"


test:python36:
  stage: test
  before_script:
    - *install_pyenv
  script:
    - pyenv install 3.6
    - pyenv shell 3.6
    - pip install tox
    - tox -e py36-normal

test:python37:
  stage: test
  before_script:
    - *install_pyenv
  script:
    - pyenv install 3.7
    - pyenv shell 3.7
    - pip install tox
    - tox -e py37-normal
      
      
test:python38:
  stage: test
  before_script:
    - *install_pyenv
  script:
    - pyenv install 3.8
    - pyenv shell 3.8
    - pip install tox
    - tox -e py38-normal
