stages:
  - test


.install_deps: &install_deps
  - pip install virtualenv
  - export VENV_LOCATION=/opt/venv
  - virtualenv $VENV_LOCATION
  - export PATH="$VENV_LOCATION/bin:$PATH"
  - pip install -r requirements-dev.txt


test:python36:
  image: python:3.6-slim
  cache:
    key:
      files:
        - requirements.txt
        - requirements-dev.txt
      paths:
        - /opt/venv
  stage: test
  before_script:
    - *install_deps
  script:
    - pytest


test:python37:
  image: python:3.7-slim
  cache:
    key:
      files:
        - requirements.txt
        - requirements-dev.txt
      paths:
        - /opt/venv
  stage: test
  before_script:
    - *install_deps
  script:
    - pytest
      
      
test:python38:
  image: python:3.8-slim
  cache:
    key:
      files:
        - requirements.txt
        - requirements-dev.txt
      paths:
        - /opt/venv
  stage: test
  before_script:
    - *install_deps
  script:
    - pytest


test:python39:
  image: python:3.9-slim
  cache:
    key:
      files:
        - requirements.txt
        - requirements-dev.txt
      paths:
        - /opt/venv
  stage: test
  before_script:
    - *install_deps
  script:
    - pytest
