stages:
  - test

image: alpine:latest

.install_pyenv: &install_pyenv
  - apk update
  - apk add --no-cache bzip2-dev coreutils dpkg-dev dpkg expat-dev \
    findutils gcc gdbm-dev libc-dev libffi-dev libnsl-dev libtirpc-dev \
    linux-headers make ncurses-dev openssl-dev pax-utils readline-dev \
    sqlite-dev tcl-dev tk tk-dev util-linux-dev xz-dev zlib-dev git curl \
    bash
  - curl https://pyenv.run | bash
  - exec $SHELL


test:
  stage: test
  before_script:
    - *install_pyenv
  script:
    - pyenv install 3.6
    - pyenv shell 3.6
    - pip install tox
    - tox -e py36-normal

test:python37:
  stage: test
  before_script:
    - *install_pyenv
  script:
    - pyenv install 3.7
    - pyenv shell 3.7
    - pip install tox
    - tox -e py37-normal
      
      
test:python38:
  stage: test
  before_script:
    - *install_pyenv
  script:
    - pyenv install 3.8
    - pyenv shell 3.8
    - pip install tox
    - tox -e py38-normal
