stages:
  - test


.install_deps: &install_deps
  - pip install virtualenv
  - virtualenv .venv
  - export PATH="$(pwd)/.venv/bin:$PATH"
  - pip install -r requirements-dev.txt


test:python36:
  image: python:3.6-slim
  stage: test
  before_script:
    - *install_deps
  script:
    - pytest


test:python37:
  image: python:3.7-slim
  stage: test
  before_script:
    - *install_deps
  script:
    - pytest
      
      
test:python38:
  image: python:3.8-slim
  stage: test
  before_script:
    - *install_deps
  script:
    - pytest


test:python39:
  image: python:3.9-slim
  stage: test
  before_script:
    - *install_deps
  script:
    - pytest
