# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/Flagsmith/flagsmith/main/sdk/evaluation-context.json
#   timestamp: 2025-10-10T16:01:57+00:00

from __future__ import annotations

from typing import Any, Dict, Generic, List, Literal, Optional, Union

from typing_extensions import NotRequired, TypedDict

from flag_engine.segments.types import (
    ConditionOperator,
    ContextValue,
    MetadataT,
    RuleType,
)


class EnvironmentContext(TypedDict):
    key: str
    name: str


class FeatureValue(TypedDict):
    value: Any
    weight: float


class IdentityContext(TypedDict):
    identifier: str
    key: str
    traits: NotRequired[Dict[str, ContextValue]]


class StrValueSegmentCondition(TypedDict):
    property: str
    operator: ConditionOperator
    value: str


class InOperatorSegmentCondition(TypedDict):
    property: str
    operator: Literal["IN"]
    value: List[str]


SegmentCondition = Union[StrValueSegmentCondition, InOperatorSegmentCondition]


class SegmentRule(TypedDict):
    type: RuleType
    conditions: NotRequired[List[SegmentCondition]]
    rules: NotRequired[List[SegmentRule]]


class FeatureContext(TypedDict):
    key: str
    feature_key: str
    name: str
    enabled: bool
    value: Any
    variants: NotRequired[List[FeatureValue]]
    priority: NotRequired[float]


class SegmentContext(TypedDict, Generic[MetadataT]):
    key: str
    name: str
    rules: List[SegmentRule]
    overrides: NotRequired[List[FeatureContext]]
    metadata: NotRequired[MetadataT]


class EvaluationContext(TypedDict, Generic[MetadataT]):
    environment: EnvironmentContext
    identity: NotRequired[Optional[IdentityContext]]
    segments: NotRequired[Dict[str, SegmentContext[MetadataT]]]
    features: NotRequired[Dict[str, FeatureContext]]
